using System.Text;

namespace Stasis.Compiler.IR.Cranelift;

/// <summary>
/// Builder for Cranelift modules.
/// Generates CLIF (Cranelift Intermediate Format) text representation.
///
/// Note: This is a scaffolding implementation that generates CLIF text.
/// Full implementation will use native Cranelift bindings for JIT compilation.
/// </summary>
public sealed class CraneliftModuleBuilder : IDisposable
{
    private readonly string _moduleName;
    private readonly StringBuilder _globals = new();
    private readonly StringBuilder _functions = new();
    private readonly List<string> _functionNames = new();
    private readonly CraneliftTypeMapper _typeMapper = new();
    private int _globalCounter;

    public CraneliftModuleBuilder(string moduleName)
    {
        _moduleName = moduleName;
    }

    public CraneliftTypeMapper TypeMapper => _typeMapper;

    /// <summary>
    /// Defines a global data section.
    /// </summary>
    public void DefineGlobalData(string name, int size)
    {
        _globals.AppendLine($"; Global: {name} ({size} bytes)");
        _globals.AppendLine($"gv{_globalCounter} = symbol colocated u0:{_globalCounter} ; {name}");
        _globalCounter++;
    }

    /// <summary>
    /// Defines a function signature (stub without body).
    /// </summary>
    public void DefineFunction(string name, CraneliftTypeMapper.ClifType returnType, params CraneliftTypeMapper.ClifType[] paramTypes)
    {
        _functionNames.Add(name);
        var paramStr = string.Join(", ", paramTypes.Select(FormatType));
        var retStr = FormatReturnType(returnType);
        _functions.AppendLine($"function %{name}({paramStr}){retStr} windows_fastcall {{");
        _functions.AppendLine($"block0:");
        _functions.AppendLine($"    ; TODO: function body");
        if (returnType != CraneliftTypeMapper.ClifType.Void)
        {
            _functions.AppendLine($"    v0 = iconst.i32 0");
            _functions.AppendLine($"    return v0");
        }
        else
        {
            _functions.AppendLine($"    return");
        }
        _functions.AppendLine($"}}");
        _functions.AppendLine();
    }

    /// <summary>
    /// Defines a function with a complete body.
    /// </summary>
    public void DefineFunctionWithBody(
        string name,
        CraneliftTypeMapper.ClifType returnType,
        CraneliftTypeMapper.ClifType[] paramTypes,
        string body)
    {
        _functionNames.Add(name);
        var paramStr = string.Join(", ", paramTypes.Select(FormatType));
        var retStr = FormatReturnType(returnType);
        _functions.AppendLine($"function %{name}({paramStr}){retStr} windows_fastcall {{");
        _functions.Append(body);
        _functions.AppendLine($"}}");
        _functions.AppendLine();
    }

    /// <summary>
    /// Emits the module as CLIF text.
    /// </summary>
    public string EmitToString()
    {
        var sb = new StringBuilder();
        sb.AppendLine($"; Cranelift module: {_moduleName}");
        sb.AppendLine($"; Generated by Stasis compiler");
        sb.AppendLine();

        if (_globals.Length > 0)
        {
            sb.AppendLine("; === Globals ===");
            sb.Append(_globals);
            sb.AppendLine();
        }

        if (_functions.Length > 0)
        {
            sb.AppendLine("; === Functions ===");
            sb.Append(_functions);
        }

        return sb.ToString();
    }

    public void Dispose()
    {
        // Nothing to dispose in scaffolding implementation
    }

    private static string FormatType(CraneliftTypeMapper.ClifType type) =>
        type switch
        {
            CraneliftTypeMapper.ClifType.Void => "void",
            CraneliftTypeMapper.ClifType.I8 => "i8",
            CraneliftTypeMapper.ClifType.I16 => "i16",
            CraneliftTypeMapper.ClifType.I32 => "i32",
            CraneliftTypeMapper.ClifType.I64 => "i64",
            CraneliftTypeMapper.ClifType.F32 => "f32",
            CraneliftTypeMapper.ClifType.F64 => "f64",
            CraneliftTypeMapper.ClifType.B1 => "b1",
            CraneliftTypeMapper.ClifType.R64 => "r64",
            _ => "i32"
        };

    private static string FormatReturnType(CraneliftTypeMapper.ClifType type)
    {
        if (type == CraneliftTypeMapper.ClifType.Void)
            return string.Empty;
        if (type == CraneliftTypeMapper.ClifType.I32)
            return " -> i32";
        return $" -> {FormatType(type)}";
    }
}
