using System.Text.RegularExpressions;
using System.Xml.Linq;

namespace Stasis.SvgValidator;

public static partial class Program
{
    private static readonly XNamespace SvgNs = "http://www.w3.org/2000/svg";
    private static readonly XNamespace XlinkNs = "http://www.w3.org/1999/xlink";

    // Rule 5: Allowed elements (basic shapes, paths, groups, gradients)
    private static readonly HashSet<string> AllowedElements = new(StringComparer.OrdinalIgnoreCase)
    {
        "svg", "g", "defs", "title", "desc",
        "rect", "circle", "ellipse", "line", "polyline", "polygon", "path",
        "linearGradient", "radialGradient", "stop"
    };

    // Rule 6: Forbidden elements
    private static readonly HashSet<string> ForbiddenElements = new(StringComparer.OrdinalIgnoreCase)
    {
        "filter", "feBlend", "feColorMatrix", "feComponentTransfer", "feComposite",
        "feConvolveMatrix", "feDiffuseLighting", "feDisplacementMap", "feDropShadow",
        "feFlood", "feGaussianBlur", "feImage", "feMerge", "feMergeNode", "feMorphology",
        "feOffset", "feSpecularLighting", "feTile", "feTurbulence",
        "mask", "clipPath", "pattern",
        "image", "use", "symbol", "marker", "switch", "foreignObject"
    };

    // Rule 12/13: Forbidden elements for text and animation
    private static readonly HashSet<string> TextElements = new(StringComparer.OrdinalIgnoreCase)
    {
        "text", "tspan", "textPath", "font", "glyph", "missing-glyph"
    };

    private static readonly HashSet<string> AnimationElements = new(StringComparer.OrdinalIgnoreCase)
    {
        "animate", "animateMotion", "animateTransform", "animateColor", "set", "mpath"
    };

    // Rule 11: Autogenerated ID patterns to reject
    [GeneratedRegex(@"^(path|rect|circle|ellipse|line|polygon|polyline|g|layer|Layer_|SVGID_|_x[0-9A-Fa-f]+_)\d*$", RegexOptions.IgnoreCase)]
    private static partial Regex AutogeneratedIdPattern();

    // Rule 2: Relative/viewport units to reject
    [GeneratedRegex(@"(\d+\.?\d*)\s*(em|rem|%|vh|vw|vmin|vmax|ex|ch)", RegexOptions.IgnoreCase)]
    private static partial Regex RelativeUnitPattern();

    // Rule 16: Inherited/computed color values
    private static readonly HashSet<string> ForbiddenColorValues = new(StringComparer.OrdinalIgnoreCase)
    {
        "inherit", "currentColor", "initial", "unset"
    };

    public static int Main(string[] args)
    {
        if (args.Length == 0)
        {
            Console.Error.WriteLine("Usage: Stasis.SvgValidator <path> [path2] ...");
            Console.Error.WriteLine("       Stasis.SvgValidator --dir <directory>");
            return 1;
        }

        var files = new List<string>();

        if (args[0] == "--dir" && args.Length >= 2)
        {
            var dir = args[1];
            if (!Directory.Exists(dir))
            {
                Console.Error.WriteLine($"Directory not found: {dir}");
                return 1;
            }
            files.AddRange(Directory.GetFiles(dir, "*.svg", SearchOption.AllDirectories));
        }
        else
        {
            files.AddRange(args);
        }

        if (files.Count == 0)
        {
            Console.WriteLine("No SVG files found.");
            return 0;
        }

        var totalErrors = 0;
        var validatedCount = 0;

        foreach (var file in files)
        {
            if (!File.Exists(file))
            {
                Console.Error.WriteLine($"File not found: {file}");
                totalErrors++;
                continue;
            }

            var errors = ValidateSvg(file);
            validatedCount++;

            if (errors.Count > 0)
            {
                Console.Error.WriteLine($"\n{file}:");
                foreach (var error in errors)
                {
                    Console.Error.WriteLine($"  [Rule {error.RuleNumber:D2}] {error.Message}");
                }
                totalErrors += errors.Count;
            }
        }

        Console.WriteLine($"\nValidated {validatedCount} SVG file(s), {totalErrors} error(s).");

        // Rule 20: Fail pipeline on any violation
        return totalErrors > 0 ? 1 : 0;
    }

    public static List<ValidationError> ValidateSvg(string path)
    {
        var errors = new List<ValidationError>();

        XDocument doc;
        try
        {
            doc = XDocument.Load(path);
        }
        catch (Exception ex)
        {
            errors.Add(new ValidationError(20, $"Failed to parse SVG: {ex.Message}"));
            return errors;
        }

        var root = doc.Root;
        if (root == null || root.Name.LocalName != "svg")
        {
            errors.Add(new ValidationError(20, "Root element must be <svg>"));
            return errors;
        }

        // Rule 1: Fixed viewBox required
        var viewBox = root.Attribute("viewBox")?.Value;
        if (string.IsNullOrWhiteSpace(viewBox))
        {
            errors.Add(new ValidationError(1, "Missing viewBox attribute on <svg>"));
        }

        // Collect all IDs for uniqueness check (Rule 10)
        var allIds = new Dictionary<string, int>(StringComparer.Ordinal);

        // Validate all elements recursively
        ValidateElement(root, errors, allIds, isRoot: true);

        // Rule 10: Check for duplicate IDs
        foreach (var kvp in allIds.Where(x => x.Value > 1))
        {
            errors.Add(new ValidationError(10, $"Duplicate id=\"{kvp.Key}\" appears {kvp.Value} times"));
        }

        // Rule 8: Check stroke consistency
        ValidateStrokeConsistency(root, errors);

        return errors;
    }

    private static void ValidateElement(XElement element, List<ValidationError> errors, Dictionary<string, int> allIds, bool isRoot = false)
    {
        var localName = element.Name.LocalName;

        // Skip namespace declarations and processing instructions
        if (element.Name.Namespace != SvgNs && element.Name.Namespace != XNamespace.None && !isRoot)
        {
            // Allow non-SVG namespace elements but don't validate them deeply
            return;
        }

        // Rule 5/6: Check element is allowed
        if (!isRoot || localName != "svg")
        {
            if (ForbiddenElements.Contains(localName))
            {
                errors.Add(new ValidationError(6, $"Forbidden element <{localName}>"));
            }
            else if (TextElements.Contains(localName))
            {
                errors.Add(new ValidationError(12, $"Text element <{localName}> not allowed (convert to paths)"));
            }
            else if (AnimationElements.Contains(localName))
            {
                errors.Add(new ValidationError(13, $"Animation element <{localName}> not allowed"));
            }
            else if (!AllowedElements.Contains(localName))
            {
                errors.Add(new ValidationError(5, $"Element <{localName}> not in allowed set"));
            }
        }

        // Check attributes
        foreach (var attr in element.Attributes())
        {
            var attrName = attr.Name.LocalName;
            var attrValue = attr.Value;

            // Rule 2: No relative units
            if (RelativeUnitPattern().IsMatch(attrValue))
            {
                errors.Add(new ValidationError(2, $"Relative unit in {localName}/@{attrName}=\"{attrValue}\""));
            }

            // Rule 7: No transforms (must be flattened)
            if (attrName == "transform" && !string.IsNullOrWhiteSpace(attrValue))
            {
                errors.Add(new ValidationError(7, $"Transform not flattened on <{localName}>: transform=\"{attrValue}\""));
            }

            // Rule 10/11: ID validation
            if (attrName == "id")
            {
                if (!allIds.TryAdd(attrValue, 1))
                {
                    allIds[attrValue]++;
                }

                if (AutogeneratedIdPattern().IsMatch(attrValue))
                {
                    errors.Add(new ValidationError(11, $"Autogenerated id=\"{attrValue}\" on <{localName}>"));
                }
            }

            // Rule 13: No CSS animations in style
            if (attrName == "style" && ContainsCssAnimation(attrValue))
            {
                errors.Add(new ValidationError(13, $"CSS animation in style attribute on <{localName}>"));
            }

            // Rule 16: No inherited/computed colors
            if (IsColorAttribute(attrName) && ForbiddenColorValues.Contains(attrValue.Trim()))
            {
                errors.Add(new ValidationError(16, $"Inherited color value {attrName}=\"{attrValue}\" on <{localName}>"));
            }

            // Rule 17: No external references
            if (attr.Name.Namespace == XlinkNs && attrName == "href")
            {
                if (IsExternalReference(attrValue))
                {
                    errors.Add(new ValidationError(17, $"External reference xlink:href=\"{attrValue}\""));
                }
            }
            if (attrName == "href" && IsExternalReference(attrValue))
            {
                errors.Add(new ValidationError(17, $"External reference href=\"{attrValue}\""));
            }
        }

        // Recurse into children
        foreach (var child in element.Elements())
        {
            ValidateElement(child, errors, allIds, isRoot: false);
        }
    }

    private static void ValidateStrokeConsistency(XElement root, List<ValidationError> errors)
    {
        // Rule 8: All strokes must be consistently scaling or non-scaling
        var vectorEffects = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var elem in root.DescendantsAndSelf())
        {
            var ve = elem.Attribute("vector-effect")?.Value;
            if (!string.IsNullOrEmpty(ve))
            {
                vectorEffects.Add(ve);
            }
            else
            {
                // Elements with stroke but no vector-effect default to "none" (scaling)
                var stroke = elem.Attribute("stroke")?.Value;
                if (!string.IsNullOrWhiteSpace(stroke) && stroke != "none")
                {
                    vectorEffects.Add("none");
                }
            }
        }

        if (vectorEffects.Count > 1)
        {
            errors.Add(new ValidationError(8, $"Mixed stroke scaling: found vector-effect values [{string.Join(", ", vectorEffects)}]"));
        }
    }

    private static bool IsColorAttribute(string attrName)
    {
        return attrName is "fill" or "stroke" or "stop-color" or "flood-color" or "lighting-color";
    }

    private static bool ContainsCssAnimation(string style)
    {
        var lower = style.ToLowerInvariant();
        return lower.Contains("animation") || lower.Contains("@keyframes") || lower.Contains("transition");
    }

    private static bool IsExternalReference(string href)
    {
        if (string.IsNullOrWhiteSpace(href)) return false;
        // Internal references start with #
        if (href.StartsWith('#')) return false;
        // Data URIs are embedded, not external
        if (href.StartsWith("data:", StringComparison.OrdinalIgnoreCase)) return false;
        // Anything else is external
        return true;
    }
}

public record ValidationError(int RuleNumber, string Message);
