[package]
name = "stasis_android_bridge"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "android_workshop_compile"
path = "src/android_workshop_compile.rs"

[dependencies]
stasis_compiler = { path = "../stasis_compiler" }
stasis_assets = { path = "../stasis_assets" }
serde_json.workspace = true
