#!/usr/bin/env python3
"""Generate and verify Brickout Defense's bounded, sample-owned image catalog."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys


SAMPLE_ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = SAMPLE_ROOT / "assets" / "asset_catalog.json"
LINEAGE_PATH = SAMPLE_ROOT / "assets" / "original" / "asset_lineage.json"
CATALOG_SOURCE = SAMPLE_ROOT / "src" / "brickout_defense_asset_catalog.stasis"
ANIMATION_SOURCE = SAMPLE_ROOT / "src" / "brickout_defense_animations.stasis"


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def verify_assets(catalog: dict, lineage: dict) -> None:
    assets_root = SAMPLE_ROOT / "assets" / "original"
    lineage_rows = {row["path"]: row for row in lineage["assets"]}
    actual_paths = {
        path.relative_to(assets_root).as_posix()
        for path in assets_root.rglob("*")
        if path.is_file() and path != LINEAGE_PATH
    }
    if actual_paths != set(lineage_rows):
        missing = sorted(set(lineage_rows) - actual_paths)
        extra = sorted(actual_paths - set(lineage_rows))
        raise ValueError(f"asset lineage paths differ: missing={missing[:4]} extra={extra[:4]}")

    for relative, row in lineage_rows.items():
        data = (assets_root / relative).read_bytes()
        if len(data) != row["bytes"] or hashlib.sha256(data).hexdigest() != row["sha256"]:
            raise ValueError(f"recovered source asset changed: {relative}")

    rows = catalog["assets"]
    if len(rows) != catalog["image_count"]:
        raise ValueError("catalog image_count does not match its rows")
    if len({row["name"] for row in rows}) != len(rows):
        raise ValueError("catalog asset names must be unique")
    if [row["id"] for row in rows] != list(range(len(rows))):
        raise ValueError("catalog ids must be contiguous and ordered")
    for row in rows:
        source = lineage_rows.get(row["path"].removeprefix("assets/original/"))
        if source is None or source["bytes"] != row["bytes"] or source["sha256"] != row["sha256"]:
            raise ValueError(f"catalog entry does not match its source lineage: {row['path']}")
        if row["width"] <= 0 or row["height"] <= 0:
            raise ValueError(f"catalog dimensions must be positive: {row['path']}")

    frame_total = sum(group["frame_count"] for group in catalog["animations"])
    if frame_total != catalog["animation_frame_count"]:
        raise ValueError("animation frame total does not match its manifest")
    if frame_total != 597:
        raise ValueError(f"expected 597 recovered animation frames, got {frame_total}")
    for group in catalog["animations"]:
        ids = group["asset_ids"]
        expected_function = f"original_{group['name']}_frame"
        if group["frame_function"] != expected_function:
            raise ValueError(
                f"animation frame function must be {expected_function}: {group['name']}"
            )
        if group["array"] != f"original_{group['name']}_frames":
            raise ValueError(f"animation frame array name is not canonical: {group['name']}")
        if len(ids) != group["frame_count"] or any(index < 0 or index >= len(rows) for index in ids):
            raise ValueError(f"invalid animation frame list: {group['name']}")
        if any(rows[index]["role"] != "animation" for index in ids):
            raise ValueError(f"animation refers to a non-animation image: {group['name']}")


def render_catalog_source(catalog: dict) -> str:
    rows = catalog["assets"]
    lines = [
        "// Generated by tools/build_asset_catalog.py. Do not edit by hand.",
        'import "/vendor/stasis/stdlib/graphics.stasis";',
        "",
        f"const BRICKOUT_DEFENSE_ASSET_COUNT: i32 = {len(rows)};",
    ]
    for row in rows:
        lines.append(f"const {row['name']}: i32 = {row['id']};")
    lines.extend(
        [
            "",
            "struct BrickoutDefenseAssetLoader {",
            "    current: ImageAsset;",
            "    next_index: i32;",
            "    failed_index: i32;",
            "    ready: bool;",
            "    failed: bool;",
            "}",
            "",
            "global brickout_defense_catalog_sprites: Sprite[BRICKOUT_DEFENSE_ASSET_COUNT];",
            "global brickout_defense_catalog_loader: BrickoutDefenseAssetLoader;",
            "",
            "function brickout_defense_catalog_request(index: i32): bool {",
        ]
    )
    for row in rows:
        lines.append(
            f"    if (index == {row['id']}) {{"
        )
        lines.append(
            f"        return brickout_defense_catalog_loader.current.load_image("
            f"\"{row['path']}\", {row['width']}, {row['height']});"
        )
        lines.append("    }")
    lines.extend(
        [
            "    return false;",
            "}",
            "",
            "function brickout_defense_catalog_poll(): void {",
            "    if (brickout_defense_catalog_loader.ready || brickout_defense_catalog_loader.failed) {",
            "        return;",
            "    }",
            "    if (brickout_defense_catalog_loader.next_index >= BRICKOUT_DEFENSE_ASSET_COUNT) {",
            "        brickout_defense_catalog_loader.ready = true;",
            "        return;",
            "    }",
            "    if (brickout_defense_catalog_loader.current.state == AssetState.None) {",
            "        if (!brickout_defense_catalog_request(brickout_defense_catalog_loader.next_index)) {",
            "            brickout_defense_catalog_loader.failed_index = brickout_defense_catalog_loader.next_index;",
            "            brickout_defense_catalog_loader.failed = true;",
            "        }",
            "        return;",
            "    }",
            "    let state: AssetState = brickout_defense_catalog_loader.current.status();",
            "    if (state == AssetState.Failed || state == AssetState.Cancelled) {",
            "        brickout_defense_catalog_loader.failed_index = brickout_defense_catalog_loader.next_index;",
            "        brickout_defense_catalog_loader.failed = true;",
            "        return;",
            "    }",
            "    if (state == AssetState.Loaded) {",
            "        if (!brickout_defense_catalog_loader.current.publish(brickout_defense_catalog_sprites[brickout_defense_catalog_loader.next_index])) {",
            "            brickout_defense_catalog_loader.failed_index = brickout_defense_catalog_loader.next_index;",
            "            brickout_defense_catalog_loader.failed = true;",
            "            return;",
            "        }",
            "        brickout_defense_catalog_loader.next_index += 1;",
            "        if (brickout_defense_catalog_loader.next_index >= BRICKOUT_DEFENSE_ASSET_COUNT) {",
            "            brickout_defense_catalog_loader.ready = true;",
            "        }",
            "    }",
            "}",
            "",
            "function brickout_defense_catalog_loaded_count(): i32 {",
            "    return brickout_defense_catalog_loader.next_index;",
            "}",
            "",
            "function brickout_defense_catalog_failed(): bool {",
            "    return brickout_defense_catalog_loader.failed;",
            "}",
            "",
            "function brickout_defense_catalog_progress_percent(): i32 {",
            "    return brickout_defense_catalog_loader.next_index * 100 / BRICKOUT_DEFENSE_ASSET_COUNT;",
            "}",
            "",
            "function brickout_defense_catalog_reference(index: i32): SpriteRef {",
            "    if (index < 0 || index >= BRICKOUT_DEFENSE_ASSET_COUNT) {",
            "        return SpriteRef.Invalid;",
            "    }",
            "    return brickout_defense_catalog_sprites[index].reference();",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def render_animation_source(catalog: dict) -> str:
    rows = catalog["assets"]
    lines = [
        "// Generated by tools/build_asset_catalog.py from the recovered 2016 frame manifest.",
        'import "brickout_defense_asset_catalog.stasis";',
        "",
    ]
    for group in catalog["animations"]:
        lines.append(f"global {group['array']}: i32[{group['frame_count']}];")
    lines.extend(["", "function original_load_animation_assets(): void {"])
    for group in catalog["animations"]:
        for frame, asset_id in enumerate(group["asset_ids"]):
            lines.append(f"    {group['array']}[{frame}] = {rows[asset_id]['name']};")
    lines.extend(["}", ""])
    for group in catalog["animations"]:
        function_name = "original_" + group["name"] + "_frame"
        count = group["frame_count"]
        lines.extend(
            [
                f"function {function_name}(frame: i32): i32 {{",
                f"    let index: i32 = frame % {count};",
                "    if (index < 0) {",
                f"        index += {count};",
                "    }",
                f"    return {group['array']}[index];",
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate both Stasis source modules")
    args = parser.parse_args()
    catalog = read_json(CATALOG_PATH)
    lineage = read_json(LINEAGE_PATH)
    verify_assets(catalog, lineage)
    expected = {
        CATALOG_SOURCE: render_catalog_source(catalog),
        ANIMATION_SOURCE: render_animation_source(catalog),
    }
    if args.write:
        for path, content in expected.items():
            path.write_text(content, encoding="utf-8", newline="\n")
        print(f"generated {len(catalog['assets'])} image catalog entries and {catalog['animation_frame_count']} animation frames")
        return 0
    mismatches = [path for path, content in expected.items() if not path.is_file() or path.read_text(encoding="utf-8") != content]
    if mismatches:
        for path in mismatches:
            print(f"generated source is stale: {path.relative_to(SAMPLE_ROOT)}", file=sys.stderr)
        print("run python tools/build_asset_catalog.py --write to regenerate", file=sys.stderr)
        return 1
    print(f"verified {lineage['asset_count']} recovered files, {len(catalog['assets'])} images, and {catalog['animation_frame_count']} animation frames")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
